services:
  backend:
    build:
      context: ./backend
    container_name: mtm_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: mini_task_manager
      DB_USERNAME: mini_user
      DB_PASSWORD: mini_password

      JWT_TTL: 60
    volumes:
      - ./backend:/var/www

  postgres:
    image: postgres:16-alpine
    container_name: mtm_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mini_task_manager
      POSTGRES_USER: mini_user
      POSTGRES_PASSWORD: mini_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mini_user -d mini_task_manager"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./web
    container_name: mtm_web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  postgres_data:
